spring:
  application:
    name: producer
server:
  port: 8082

eurekaServer:
  host: register1
  port: 8081

eureka:
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 10

  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    service-url:
      defaultZone: http://${eurekaServer.host}:${eurekaServer.port}/eureka